name: iot-agent
version: "0.4"
summary: IoT Device Management Agent using MQTT
description: |
  The IoT Agent enrolls a device with the IoT Identity service and receives credentials to access the MQTT broker.
  Via MQTT, it establishes communication with an IoT Management service, so the device can be remotely monitored and managed over a
  secure connection.

  The agent is intended to operate on a device running Ubuntu or Ubuntu Core with snapd enabled.
  The device management features are implemented using the snapd REST API.
confinement: strict
grade: stable
base: core20

apps:
  mqtt:
    command: agent
    daemon: simple
    plugs:
      - network
      - network-bind
      #- snapd-control    # it needs these privileged interfaces
      #- shutdown         # but they trigger a manual store review

parts:
  client:
    plugin: go
    source: .
    override-build: |
      mkdir -p ${SNAPCRAFT_PART_BUILD}/src/github.com/CanonicalLtd
      ln -sf ${SNAPCRAFT_PART_SRC} \
             ${SNAPCRAFT_PART_BUILD}/src/github.com/CanonicalLtd/iot-agent
      export GOPATH="${PWD}"
      export GOBIN="${PWD}/bin"
      PKG=github.com/CanonicalLtd/iot-agent
      mkdir -p ${GOBIN}
      cd ${GOPATH}/src/${PKG}
      ./get-deps.sh
      go install ./...

      mkdir -p ${SNAPCRAFT_PART_INSTALL}/bin
      go build -o \
         ${SNAPCRAFT_PART_INSTALL}/bin/agent \
         github.com/CanonicalLtd/iot-agent/cmd/agent
      go build -o \
         ${SNAPCRAFT_PART_INSTALL}/bin/configure \
         github.com/CanonicalLtd/iot-agent/cmd/configure

build-packages:
  - git
  - gcc
